on: 
  push: 
    branches:
    - main

jobs: 
  updateAuthor: 
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Extract git commit data
      uses: rlespinasse/git-commit-data-action@v1.x

    - name: Update author information
      run: echo ${ env.GIT_COMMIT_AUTHOR_NAME } > CODEOWNERS

    - name: Raise PR
      uses: peter-evans/create-pull-request@v3
      with:
        branch: "auto-pr-branch"
        base: main
        title: "Demo for auto PR"
        committer: "${ env.GIT_COMMIT_AUTHOR_NAME } <${ env.GIT_COMMIT_AUTHOR_EMAIL }>"
        author: "${ env.GIT_COMMIT_AUTHOR_NAME } <${ env.GIT_COMMIT_AUTHOR_EMAIL }>"
        body: "This is to show automatic PR creation for python"
        token: "${{ secrets.GITHUB_TOKEN }}"
        delete-branch: true
    
    # Auto-assign the PR to a specific user or team using kentaro-m/auto-assign
    - name: Auto-assign PR
      uses: kentaro-m/auto-assign@v1
      with:
        assignees: |
          atiar-gt
          mominurGT
        reviewers: |
          kawser-gt
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
