on: 
  create:
    branches: ['staging']
jobs: 
  pull-request:
    name: Open PR to main
    runs-on: ubuntu-latest

    steps: 
    - name: checking out code
      uses: actions/checkout@v2 

    - name: extract git commit data
      uses: rlespinasse/git-commit-data-action@v1.x
      
    - name: Update author information
      run: echo ${( env.GIT_COMMIT_AUTHOR_NAME )} > AUTHOR

    - name: Raise PR
      uses: peter-evans/create-pull-request@v3
      with:
        destination_branch: "main"
        pr_title: "Pulling ${{ github.ref }} into main"
        pr_body: "👑 *An automated PR*"
        pr_reviewer: "atiar-gt"
        pr_draft: true
        github_token: ${{ secrets.GITHUB_TOKEN }}
        delete-branch: true
